version: 2
updates:
  # 1. Python dependencies from pyproject.toml and uv.lock
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "automerge"

  # 2. GitHub Actions in .github/workflows/
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "automerge"
