[project]
name = "yapc"
version = "0.0.1"
description = "A Git/Cruft-only Cookiecutter template for initializing new Python projects."
authors = [{ name = "Visesh P", email = "viseshrprasad@gmail.com" }]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["cookiecutter", "template", "uv", "cli", "yapc"]
requires-python = ">=3.10,<4.0"
dependencies = []
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Code Generators",
]

[project.urls]
Repository = "https://github.com/viseshrp/yapc"
Documentation = "https://github.com/viseshrp/yapc"
Homepage = "https://github.com/viseshrp/yapc"

[dependency-groups]
dev = [
    "cookiecutter>=2.7.1",
    "pytest>=9.1.1",
    "pre-commit>=4.6.1",
    "pytest-cookies>=0.7.0",
    "tox-uv>=1.36.0",
    "deptry>=0.25.1",
    "tomli>=2.4.0",
    "ty>=0.0.63",
    "pyyaml>=6.0.3",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ty.src]
include = ["hooks", "tests"]

[tool.ty.environment]
python-version = "3.10"

[tool.ty.rules]
unused-type-ignore-comment = "error"

[tool.deptry]
extend_exclude = [
    "\\{\\{cookiecutter\\.project_name\\}\\}/.*",
]

[tool.ruff]
target-version = "py310"
line-length = 120
fix = true
exclude = [
    "build",
    "dist",
    ".venv",
    "venv",
    "__pycache__",
    "docs/_build",
]

[tool.ruff.lint]
select = [
    "YTT", # flake8-2020
    "S", # flake8-bandit
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "T10", # flake8-debugger
    "SIM", # flake8-simplify
    "I", # isort
    "C90", # mccabe
    "E", "W", # pycodestyle
    "F", # pyflakes
    "PGH", # pygrep-hooks
    "UP", # pyupgrade
    "RUF", # ruff
    "TRY", # tryceratops
]
ignore = [
    "S603", # `subprocess` call: check for execution of untrusted input
    "E501", # LineTooLong
    "E731", # DoNotAssignLambda
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S603"]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
