name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"
  uv-version:
    description: "uv version to use"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: {% raw %}${{ inputs.python-version }}{% endraw %}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: {% raw %}${{ inputs.uv-version }}{% endraw %}
        enable-cache: "true"
        cache-suffix: {% raw %}${{ inputs.python-version }}{% endraw %}

    - name: Cache .venv directory
      uses: actions/cache@v4
      with:
        path: .venv
        key: {% raw %}uv-venv-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}{% endraw %}
        restore-keys: |
          {% raw %}uv-venv-${{ inputs.python-version }}-{% endraw %}

    - name: Install Python dependencies
      run: uv sync --group dev
      shell: bash

    - name: Add .venv/bin to PATH
      run: echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
      shell: bash
