name: Automerge

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - labeled
      - synchronize
      - opened
      - reopened

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  automerge:
    if: github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve if opened by github-actions
        if: github.event.pull_request.user.login == 'github-actions[bot]'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          merge-method: squash
          pull-request-number: {% raw %}${{ github.event.pull_request.number }}{% endraw %}
