name: Automerge

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - reopened
  pull_request_target:
    types: [ labeled ]  # For forks & bots like Dependabot

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Debug PR info
        run: |
          {% raw %}echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"{% endraw %}

      - name: Auto-approve if opened by github-actions or dependabot
        if: |
          github.event.pull_request.user.login == 'github-actions[bot]' ||
          github.event.pull_request.user.login == 'dependabot[bot]' ||
          github.event.pull_request.user.login == 'viseshrp'
        uses: hmarr/auto-approve-action@v4
        with:
          token: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        env:
          GH_TOKEN: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
        with:
          token: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
          merge-method: squash
          pull-request-number: {% raw %}${{ github.event.pull_request.number }}{% endraw %}

      - name: Confirm automerge is enabled
        run: gh pr view {% raw %}${{ github.event.pull_request.number }}{% endraw %} --json autoMergeRequest
        env:
          GH_TOKEN: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
