name: Auto-merge Pre-commit Updates

on:
  pull_request:
    types:
      - labeled
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: |
      github.event.pull_request.head.ref == 'chore/pre-commit-update' &&
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'chore')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          merge-method: squash
