name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}

      - name: Set up Python + Environment
        uses: ./.github/actions/setup-python-env

      - name: Run code quality checks
        run: make check

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python + Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        if: {% raw %}${{ matrix.python-version == '3.13' }}{% endraw %}
        uses: codecov/codecov-action@v4
        with:
          token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}

  publish-to-testpypi:
    if: github.ref == 'refs/heads/main'
    needs: [quality, tests]
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python + Environment
        uses: ./.github/actions/setup-python-env

      - name: Build project
        run: make build

      - name: Publish to TestPyPI
        run: make publish-test
        env:
          TEST_PYPI_TOKEN: {% raw %}${{ secrets.TEST_PYPI_API_TOKEN }}{% endraw %}
