name: Main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*
  push:
    tags:
      - "v*"
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAIN_PYTHON_VERSION: '3.13'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}

      - name: Set up Python + Environment
        uses: ./.github/actions/setup-python-env

      - name: Run code quality checks
        run: make check

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python + Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Run tests
        run: make test

      - name: Upload coverage report
        if: {% raw %}${{ matrix.python-version == env.MAIN_PYTHON_VERSION }}{% endraw %}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage-html
          retention-days: 60
          if-no-files-found: error

      - name: Upload coverage to Codecov
        if: {% raw %}${{ matrix.python-version == env.MAIN_PYTHON_VERSION }}{% endraw %}
        uses: codecov/codecov-action@v5
        with:
          token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}

  publish-to-testpypi:
    if: github.ref == 'refs/heads/main'
    needs: [quality, tests]
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python + Environment
        uses: ./.github/actions/setup-python-env

      - name: Build project
        run: make build

      - name: Publish to TestPyPI
        run: make publish-test
        env:
          TEST_PYPI_TOKEN: {% raw %}${{ secrets.TEST_PYPI_API_TOKEN }}{% endraw %}
