name: "Pre-commit autoupdate"

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Run autoupdate
        run: uv run pre-commit autoupdate
        continue-on-error: true

      - name: Run pre-commit
        run: make check

      - uses: peter-evans/create-pull-request@v7
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          branch: chore-update-pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          body: |
            # Update pre-commit hooks

            - Update pre-commit hooks to the latest version.
          delete-branch: true
