name: Release to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important for hatch-vcs to see full Git history and tags

      - name: Set up Python Environment
        uses: ./.github/actions/setup-python-env

      - name: Verify tag matches project version
        run: |
          import os
          import subprocess
          import sys

          tag = os.environ.get("GITHUB_REF_NAME", "").strip()

          if tag.startswith("v"):
              tag_stripped = tag[1:]
          else:
              tag_stripped = tag

          result = subprocess.run(["uv", "run", "hatch", "version"], capture_output=True, text=True)
          project_version = result.stdout.strip()

          print(f"GitHub Tag: {tag_stripped}")
          print(f"Project Version: {project_version}")

          if tag_stripped != project_version:
              print(f"::error ::Tag version ({tag_stripped}) does not match project version ({project_version})")
              sys.exit(1)
        shell: python

      - name: Build package
        run: make build

      - name: Publish package to PyPI
        run: make publish
        env:
          UV_PUBLISH_TOKEN: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
