name: Release

on:
  workflow_dispatch:
  release:
    types: [ published ]

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # just checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for hatch-vcs to generate full version
          fetch-tags: true

      - name: Set up Python Env
        uses: ./.github/actions/setup-python-env

      - name: Run version checks
        run: make check-version

      - name: Prevent accidental dev release
        run: |
          if hatch version | grep -q dev; then
            echo "❌ Refusing to publish a dev version to PyPI"
            exit 1
          fi

      - name: Build package
        run: make build

      - name: Publish package to PyPI
        run: make publish
        env:
          PYPI_TOKEN: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
