name: Comment VHS GIF on PR

on:
  pull_request:
    paths:
      - demo.tape

permissions:
  contents: read
  pull-requests: write

jobs:
  check_demo_tape:
    name: Check if demo.tape changed
    runs-on: ubuntu-latest
    outputs:
      demo_changed: {% raw %}${{ steps.detect.outputs.changed }}{% endraw %}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes to demo.tape
        id: detect
        run: |
          {% raw %}if git diff --name-only $(git rev-parse HEAD^1) HEAD | grep -q "^demo\.tape$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi{% endraw %}

  vhs-comment:
    name: Generate and Comment demo.gif
    needs: check_demo_tape
    if: {% raw %}${{ needs.check_demo_tape.outputs.demo_changed == 'true' }}{% endraw %}
    runs-on: macos-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
          ref: {% raw %}${{ github.event.pull_request.head.ref }}{% endraw %}
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config user.name "vhs-action 📼"
          git config user.email "actions@github.com"

      - name: Set up Python + Environment
        uses: ./.github/actions/setup-python-env

      - name: Install VHS + deps
        run: brew install vhs

      - name: Generate demo.gif
        run: vhs demo.tape

      - name: Commit demo.gif to PR branch
        run: |
          git add demo.gif
          git commit -m "chore(demo): update demo.gif"
          git push
        env:
          PERSONAL_ACCESS_TOKEN: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}

      - name: Comment on PR with demo.gif
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        env:
          IMAGE_URL: {% raw %}https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.pull_request.head.ref }}/demo.gif{% endraw %}
          MESSAGE: |
            🖼️ **VHS Preview**

            Here's the updated `demo.gif` based on your changes:

            ![Demo]({0})
        with:
          repo-token: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
          message: {% raw %}${{ format(env.MESSAGE, env.IMAGE_URL) }}{% endraw %}
