name: Auto-update demo.gif

on:
  push:
    branches:
      - main
    paths:
      - demo.tape
  workflow_dispatch:

permissions:
  contents: write

jobs:
  vhs:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config user.name "vhs-action 📼"
          git config user.email "actions@github.com"

      - name: Set up Python + virtual environment
        uses: ./.github/actions/setup-python-env

      - name: Install VHS + deps
        run: brew install vhs

      - name: Generate demo.gif
        run: vhs demo.tape

      - name: Commit demo.gif if changed
        run: |
          if git diff --quiet -- demo.gif; then
            echo "✅ No changes to demo.gif"
            exit 0
          fi

          git add demo.gif
          git commit -m "chore(demo): update demo.gif"
          git push origin main
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
